name: App Staging CICD

on:
  push:
    branches:
      - development
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'README.md'
      - 'src/landing/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'


jobs:

  build_and_push:
    runs-on: self-hosted
    steps:
    - name: pull latest code
      uses: actions/checkout@v3    
      
    - name: build step
      run: cd src/app; docker build -t reg.dexpresso.exchange/staging/app:latest .

    - name: login to docker registry
      run:  echo ${{ secrets.Harbor_PASSWORD }} | docker login reg.dexpresso.exchange -u action  --password-stdin


    - name: push docker image to package registry
      run: docker push reg.dexpresso.exchange/staging/app:latest
  
  deploy:
    runs-on: self-hosted
    needs: build_and_push
    steps:
    - name: run command on remote
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_SSH_ACTION_HOST }}
        username: ${{ secrets.STAGING_SSH_ACTION_USER }}
        key: ${{ secrets.STAGING_SSH_ACTION_KEY }}
        port: ${{ secrets.STAGING_SSH_ACTION_PORT}}
        script: |
          cd /opt/docker/services/app
          echo ${{ secrets.Harbor_PASSWORD }} | docker login reg.dexpresso.exchange  -u action --password-stdin
          docker rmi -f reg.dexpresso.exchange/staging/app:latest || echo "Ok"
          docker pull reg.dexpresso.exchange/staging/app:latest
          docker-compose up -d --build
          chmod +x update.sh
          ./update.sh
