name: Landing Staging CICD

on:
  push:
    branches:
      - development
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'README.md'
      - 'src/app/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'


jobs:

  build_and_push:
    runs-on: self-hosted
    steps:
    - name: pull latest code
      uses: actions/checkout@v3    
    
    - name: build step
      run: cd src/landing; docker build -t reg.dexpresso.exchange/staging/landing:latest .

    - name: login to docker registry
      run:  echo ${{ secrets.Harbor_PASSWORD }} | docker login reg.dexpresso.exchange  -u action  --password-stdin


    - name: push docker image to package registry
      run: docker push reg.dexpresso.exchange/staging/landing:latest
  
  deploy:
    runs-on: self-hosted
    needs: build_and_push
    steps:
    - name: run command on remote
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_SSH_ACTION_HOST }}
        username: ${{ secrets.STAGING_SSH_ACTION_USER }}
        key: ${{ secrets.STAGING_SSH_ACTION_KEY }}
        port: ${{ secrets.STAGING_SSH_ACTION_PORT}}
        script: |
          cd /opt/docker/services/landing
          echo ${{ secrets.Harbor_PASSWORD }} | docker login reg.dexpresso.exchange  -u action  --password-stdin
          docker rmi -f reg.dexpresso.exchange/staging/landing:latest || echo "Ok"
          docker pull reg.dexpresso.exchange/staging/landing:latest
          export NEXT_PUBLIC_TRADE_APP_LINK=https://morabandtrade.dexpresso.exchange
          docker-compose up -d